AWSTemplateFormatVersion: "2010-09-09"
Description: 'create a public s3 bucket for web hosting'
Metadata:
  Authors:
    Description: Giorgio Carta
Resources:
  PublicS3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Join
        - ''
        - - 'public-bucket-'
          - !Ref 'AWS::AccountId'
          - '-temp'
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
      Tags:
        - Key: 'Name'
          Value: 'PublicBucket'
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref PublicS3Bucket
      PolicyDocument:
        Id: PublicBucketPolicy
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref PublicS3Bucket
                - /*
Outputs:
  BuckeName:
    Value: !Ref PublicS3Bucket
  WebsiteURL:
    Value: !GetAtt
      - PublicS3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - PublicS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content



